### ISSUE TITLE
exception inside `has_collision`

### ISSUE THREAD

**Issue by zookozcash** [str4d/zcash-pow#1]
Suspect it might have something to do with the ridiculously small args I gave…

```
zooko@spark ~/playground/zcash-pow/reference/python $ python pow.py -n 1 -k 2 -d 1
Miner starting
- n: 1
- k: 2
- d: 1
Traceback (most recent call last):
  File "pow.py", line 188, in <module>
    mine(args.n, args.k, args.d)
  File "pow.py", line 147, in mine
    x = gbp_basic(curr_digest, n, k)
  File "pow.py", line 65, in gbp_basic
    if not has_collision(X[j][0], X[k][0], i, collision_length):
  File "pow.py", line 28, in has_collision
    return reduce(lambda x, y: x and y, res)
TypeError: reduce() of empty sequence with no initial value
```

**Comment by zookozcash** [comment]
Hm.

```
zooko@spark ~/playground/zcash-pow/reference/python $ python pow.py -n 2 -k 3 -d 2
Miner starting
- n: 2
- k: 3
- d: 2
Traceback (most recent call last):
  File "pow.py", line 188, in <module>
    mine(args.n, args.k, args.d)
  File "pow.py", line 147, in mine
    x = gbp_basic(curr_digest, n, k)
  File "pow.py", line 65, in gbp_basic
    if not has_collision(X[j][0], X[k][0], i, collision_length):
  File "pow.py", line 28, in has_collision
    return reduce(lambda x, y: x and y, res)
TypeError: reduce() of empty sequence with no initial value
```

**Comment by zookozcash** [comment]
```
zooko@spark ~/playground/zcash-pow/reference/python $ python pow.py -n 32 -k 4 -d 99
Miner starting
- n: 32
- k: 4
- d: 99
Traceback (most recent call last):
  File "pow.py", line 188, in <module>
    mine(args.n, args.k, args.d)
  File "pow.py", line 147, in mine
    x = gbp_basic(curr_digest, n, k)
  File "pow.py", line 65, in gbp_basic
    if not has_collision(X[j][0], X[k][0], i, collision_length):
  File "pow.py", line 28, in has_collision
    return reduce(lambda x, y: x and y, res)
TypeError: reduce() of empty sequence with no initial value
```

**Comment by str4d** [comment]
This is probably because I have not constrained the input parameters. Per the paper, the implementation is easiest when `n/(k+1) = 0 mod 8` so we are working with integer numbers of bytes, and my implementation does leverage this.
