### ISSUE TITLE
have problem with print-soln

### ISSUE THREAD

**Issue by Arazesh** [str4d/zcash-pow#11]
Hi ,
When i use print-soln with this command 

./print-soln.py 200 9 218212
or
./print-soln.py 200 9 040000002196d61ff5b780728164a5f79d12d5c10a1f1436bcccc26f11bb781000000000177808bbff5a354013843ac855c65dd4cf8a40dca25ca2babffcfaf43e13fa130000000000000000000000000000000000000000000000000000000000000000eb2c085a6146151c04c7d48cf5c0a8f701dd4d200000000000000000000000000000000000000000

In both of them this error will be shown

Traceback (most recent call last):
  File "./print-soln.py", line 86, in <module>
    print_hashes(*generate_hashes(args.n, args.k, unhexlify(args.header)))
  File "./print-soln.py", line 51, in generate_hashes
    num_bytes = ord(header[140]) if ord(header[140]) < 253 else struct.unpack('<H', header[141:143])[0]
IndexError: string index out of range

thanks.

**Comment by Arazesh** [comment]
I think it is because of header[] size
It just has 140 length so max must be header[139] but at this line

num_bytes = ord(header[140]) if ord(header[140]) < 253 else struct.unpack('<H', header[141:143])[0]

There is header[140] and header[141:143]
