### ISSUE TITLE
Failure in progressbar plot in the final round routine

### ISSUE THREAD

**Issue by ampyx** [str4d/zcash-pow#4]
I get an error using the verbosity mode in zcash-pow. The progressbar fails to plot for some reason:

```bash
Miner starting
- n: 96
- k: 5
- d: 3

Nonce: 0
Generating first list
100% (131072 of 131072) |##############################################################################################################################################| Elapsed Time: 0:00:01 Time: 0:00:01
Round 1:
- Sorting list
- Finding collisions
100% (131072 of 131072) |##############################################################################################################################################| Elapsed Time: 0:00:01 Time: 0:00:01
Round 2:
- Sorting list
- Finding collisions
100% (130948 of 130948) |##############################################################################################################################################| Elapsed Time: 0:00:01 Time: 0:00:01
Round 3:
- Sorting list
- Finding collisions
100% (131030 of 131030) |##############################################################################################################################################| Elapsed Time: 0:00:01 Time: 0:00:01
Round 4:
- Sorting list
- Finding collisions
100% (131085 of 131085) |##############################################################################################################################################| Elapsed Time: 0:00:02 Time: 0:00:02
Final round:
- Sorting list
- Finding collisions
Traceback (most recent call last):
  File "./pow.py", line 236, in <module>
    mine(args.n, args.k, args.d)
  File "./pow.py", line 186, in mine
    solns = gbp_basic(curr_digest, n, k)
  File "./pow.py", line 112, in gbp_basic
    for i in bar(range(0, len(X)-1)):
  File "/usr/local/lib/python2.7/dist-packages/progressbar/bar.py", line 376, in __next__
    self.start()
  File "/usr/local/lib/python2.7/dist-packages/progressbar/bar.py", line 539, in start
    self.update(self.min_value, force=True)
  File "/usr/local/lib/python2.7/dist-packages/progressbar/bar.py", line 496, in update
    StdRedirectMixin.update(self, value=value)
  File "/usr/local/lib/python2.7/dist-packages/progressbar/bar.py", line 119, in update
    if self.redirect_stdout and sys.stdout.tell():
IOError: [Errno 29] Illegal seek
```

I cloned the repository, installed progressbar2 via pip and executed:
```bash
./pow.py -v 
```

**Comment by ampyx** [comment]
The following patch solves the issue
```patch
111c111
<     if DEBUG and progressbar: bar = progressbar.ProgressBar(redirect_stdout=True)
---
>     if DEBUG and progressbar: bar = progressbar.ProgressBar()
```

**Comment by str4d** [comment]
Unfortunately, I am unable to recreate your bug. I am using progressbar2 version 3.10.0; what version are you using?

**Comment by str4d** [comment]
(The `redirect_stdout=True` is necessary for the progress bar to correctly interact with the verbose output when using `./pow.py -vv`.)

**Comment by ampyx** [comment]
Apparently there was a bug in an older version of progressbar2, by updating the progressbar2 package the issue was resolved.

Thanks
